name: Build and deploy ASP.Net Core app to Azure Web App - backendSoulBeats

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Decode Firebase credentials to file (firebase.json)
        shell: powershell
        run: |
          $path = "firebase.json"
          [IO.File]::WriteAllBytes($path, [Convert]::FromBase64String("${{ secrets.AZURE_FIREBASE_SERVICE_ACCOUNT_KEY_B64 }}"))
          
          if (-Not (Test-Path $path)) {
            Write-Error "ERROR: No se creó firebase.json"
            exit 1
          }

          $length = (Get-Content $path).Length
          if ($length -eq 0) {
            Write-Error "ERROR: firebase.json está vacío"
            exit 1
          }

          Write-Output "firebase.json creado correctamente con tamaño: $length caracteres"
          Write-Output "Primera línea del archivo:"
          Get-Content $path | Select-Object -First 1

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Copy firebase.json to output folder
        run: copy firebase.json "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFE786C5C9164E28A7F4AA4424A37699 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FAACE8D80C914421A0B1CCCD17696C3D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F45422AB7A240A189EC66356F70D28E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendSoulBeats'
          slot-name: 'Production'
          package: .
